### ISSUE TITLE
gnu-plct-rv64ilp32-elf is a baremetal toolchain, but ruyi list -v show that include glibc and linux-headers

### ISSUE THREAD

**Issue by jacky-lau-1** [ruyisdk/packages-index#3]
when i invoke ruyi list -v, it show that the omponents of toolchain/gnu-plct-rv64ilp32-elf is:
### Toolchain metadata

* Target: riscv64-plct-elf
* Flavors: ['rv64ilp32']
* Components:
    - binutils 2.42
    - gcc 13.2.0
    - gdb 14.1
    - glibc 2.38
    - linux-headers 6.4

But this toolchain is bearmetal toolchain, and the directory of gnu-plct-rv64ilp32-elf don't contain any file of glibc or linux-headers.

**Comment by lazyparser** [comment]
Hi @jacky-lau-1 

Thank you for reporting the issue. You may check the latest version to see if it had been fixed. Feel free to reopen the issue if anything looks wrong.
